### ISSUE TITLE
How can I make it work for vue files?

### ISSUE THREAD

**Issue by madhurachanna** [JoosepAlviste/nvim-ts-context-commentstring#14] opened 2021-06-13 17:53 UTC

**Comment by madhurachanna** [comment] 2021-06-13 19:25
Worked with this confign in `context_commentstring`
```
            vue = {
                __default= "<!-- %s -->",
                html = "<!-- %s -->",
                javascript = "// %s",
                script = "// %s",
                css = '/* %s */',
                comment = "<!-- %s -->",
            },

```

**Comment by JoosepAlviste** [comment] 2021-06-13 19:42
Hey @madhurachanna! Something like that should work indeed, but there should be no need for configuring Vue explicitly.

If you don't mind, I would like to figure out why the defaults didn't work for you :)

Are you using the JavaScript and CSS treesitter parsers so that they are injected into Vue files? Or are you using regex highlights inside the script and style sections? If you have installed the js & css parsers, then they should be automatically injected and the default configuration should work.

Could you paste your treesitter config here?

**Comment by madhurachanna** [comment] 2021-06-14 04:23
Hey, @JoosepAlviste 

Can you add `vue = '<!-- %s -->'` inside M.config in `internal.lua` ?
By default comments works  with `javascript` and `css` section and not in `template` or `html` section of the code.

Adding just `vue = '<!-- %s -->'` works correctly.

Thank you.

**Comment by madhurachanna** [comment] 2021-06-14 05:25
My current treesitter config is
```
    context_commentstring = {
        enable = true,
        config = {
             -- Languages that have a single comment style
            typescript = '// %s',
            css = '/* %s */',
            scss = '/* %s */',
            html = '<!-- %s -->',
            svelte = '<!-- %s -->',
            vue = '<!-- %s -->',
        }
    },

```

**Comment by JoosepAlviste** [comment] 2021-06-14 07:28
Oh I see what the problem is. I have set the `commentstring` in Vue files in my own configuration in a `FileType` autocmd with `setlocal commentstring=<!--\ %s\ -->`. So that's why it worked for me.

I added `vue = '<!-- %s -->'` to the defaults and it seems to work without my extra configuration now.

I'll close this issue for now, but you can reopen it if it doesn't work or something else comes up.

Thanks for the help!

**Closed by JoosepAlviste** 2021-06-14 07:28 UTC

**Comment by madhurachanna** [comment] 2021-06-14 12:43
@JoosepAlviste . Will it be good idea to add `vue` under supported langues? in ReadMe file?
https://github.com/JoosepAlviste/nvim-ts-context-commentstring#adding-support-for-more-languages

**Comment by JoosepAlviste** [comment] 2021-06-14 12:50
@madhurachanna Of course, thanks for the reminder, added! 😄

**Comment by shubham-cpp** [comment] 2021-12-31 06:51
This is not working for vue files.
- Inside script block `commentstring` should be `// %s`
- Inside style `commentstring` should be `/* %s  */`
- Inside template block `commentstring` should be `<!-- %s -->`

I have this as a config as suggested by @madhurachanna 
```lua
	context_commentstring = {
		enable = true,
		enable_autocmd = false,
		config = {
			vue = {
				__default = "<!-- %s -->",
				html = "<!-- %s -->",
				javascript = "// %s",
				script = "// %s",
				css = "/* %s */",
				comment = "<!-- %s -->",
			},
		},
	},

```

Note: I'm using [Comment.nvim](https://github.com/numToStr/Comment.nvim) and Vue 3

**Comment by JoosepAlviste** [comment] 2021-12-31 14:56
Hey @shubham-cpp! It should work in Vue files by default without any additional configuration. Can you try this?

```lua
	context_commentstring = {
		enable = true,
		enable_autocmd = false,
	},
```

If it still doesn't work then could you open a new issue with a minimal config for reproducing it?

**Comment by shubham-cpp** [comment] 2021-12-31 15:13
the issue is persistent

> open a new issue with a minimal config for reproducing it

will do this

**Comment by shubham-cpp** [comment] 2021-12-31 15:29
<details>

<summary>Minimal Config</summary>

```lua
local packer = require("packer")
packer.init({
  enable = true,
  threshold = 0,
})
local use = packer.use
packer.reset()

use("wbthomason/packer.nvim")

use({
  "numToStr/Comment.nvim",
  config = function() 
    require('Comment').setup()
  end 
})

use({
  "nvim-treesitter/nvim-treesitter",
  run = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "html",
        "css",
        "javascript",
        "typescript",
        "tsx",
        "vue",
      },
      highlight = { enable = true, use_languagetree = true },
      context_commentstring = {
        enable = true,
        enable_autocmd = false,
        --[[ config = {
        vue = {
        __default = "// %s ",
        html = "<!-- %s -->",
        javascript = "// %s",
        script = "// %s",
        css = "/* %s */",
        comment = "// %s",
        },
        }, ]]
      },
    })
  end
})

use({"JoosepAlviste/nvim-ts-context-commentstring"})

```

</details>

Ok everything is working with minimal config, maybe its an issue from my end. Sorry for false issue  😅

**Comment by SasukeBo** [comment] 2023-03-28 05:43
> 

ensure_installed config is work for me
